#!/bin/bash
# Script 5: Open Source Manifesto Generator
# This script generates a personalized philosophy statement.
# Concepts: interactive read, string concatenation, file redirection.

echo "=========================================================="
echo "          OPEN SOURCE MANIFESTO GENERATOR                 "
echo "=========================================================="
echo "Answer three questions to define your commitment to FOSS."
echo

# Collecting interactive user input
read -p "1. Name one open-source tool you use every day: " TOOL_NAME
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM_DEF
read -p "3. Name one thing you would build and share freely: " BUILD_TARGET

# Metadata for the file
CURRENT_DATE=$(date '+%d %B %Y')
OS_USER=$(whoami)
OUTPUT_FILE="manifesto_${OS_USER}.txt"

# Generating the manifesto using redirection (>) and append (>>)
echo "MANIFESTO FOR THE ADVANCEMENT OF OPEN KNOWLEDGE" > "$OUTPUT_FILE"
echo "Generated by: $OS_USER on $CURRENT_DATE" >> "$OUTPUT_FILE"
echo "----------------------------------------------------------" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "I believe that software is more than a product; it is" >> "$OUTPUT_FILE"
echo "the cumulative wisdom of our digital era." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "To me, freedom in software translates to: $FREEDOM_DEF." >> "$OUTPUT_FILE"
echo "This is why I rely on tools like $TOOL_NAME every day." >> "$OUTPUT_FILE"
echo "In the spirit of reciprocity, I commit to building" >> "$OUTPUT_FILE"
echo "$BUILD_TARGET and sharing it with the world." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Let us continue to stand on the shoulders of giants." >> "$OUTPUT_FILE"

# Output verification
echo "----------------------------------------------------------"
echo "Manifesto saved to: $OUTPUT_FILE"
echo "----------------------------------------------------------"
cat "$OUTPUT_FILE"

# ALIAS NOTE: To call this generator quickly, add this to your.bashrc:
# alias genmanifesto='/path/to/script5.sh'
